files:
  - source: '*.md'
    ignore:
      - /1.11/
      - /js
      - /scss
      - /pages/1.7/
      - /pages/1.8/
      - /pages/1.9/
      - /pages/404/
      - /pages/search/
      - /pages/services/
      - /pages/test/
      - README.md
      - /pages/index.md
      - /cn/
      - /pages/CN/
    translation: /%two_letters_code%/%original_path%/%original_file_name%
